# Generated by Django 4.0.4 on 2022-05-15 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_categories_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
