# Generated by Django 4.0.4 on 2022-05-15 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0003_categories_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchcreaditionals',
            name='limit_date',
            field=models.TextField(),
        ),
    ]
