# Generated by Django 4.0.4 on 2022-05-15 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0007_alter_queries_status_alter_queries_translate_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='queries',
            name='limit',
            field=models.CharField(choices=[(10, 10), (20, 20), (30, 30), (40, 40), (50, 50), (60, 60), (70, 70), (80, 80), (90, 90), (100, 100)], default=10, max_length=100),
        ),
    ]
