# Generated by Django 4.0.4 on 2022-05-17 10:09

from django.db import migrations
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0010_alter_articles_text_content_alter_articles_top_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articles',
            name='text_content',
            field=mdeditor.fields.MDTextField(blank=True, null=True),
        ),
    ]
